# Generated by Django 5.1.3 on 2024-11-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_remove_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='noImage.png', upload_to=''),
        ),
    ]
